"use client";

import React from "react";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";

interface DisclaimerDialogProps {
  isOpen: boolean;
  onOpenChange: (open: boolean) => void;
  onConfirm: () => void;
}

const DisclaimerDialog: React.FC<DisclaimerDialogProps> = ({ isOpen, onOpenChange, onConfirm }) => {
  return (
    <AlertDialog open={isOpen} onOpenChange={onOpenChange}>
      <AlertDialogContent className="bg-card text-card-foreground border-border"> {/* Changed styling */}
        <AlertDialogHeader>
          <AlertDialogTitle className="text-2xl font-bold text-primary"> {/* Changed text color */}
            Important Disclaimer
          </AlertDialogTitle>
          <AlertDialogDescription className="text-muted-foreground text-md leading-relaxed"> {/* Changed text color */}
            The insights provided by the Founder Clarity Compass are generated by AI and are
            intended to be directional and thought-provoking, not prescriptive advice. They are
            based on general patterns and your responses, and may not fully capture the nuances
            of your unique situation.
            <br /><br />
            Always exercise your own judgment and consider consulting with a human expert for
            personalized guidance. Your data is handled with care and privacy.
          </AlertDialogDescription>
        </AlertDialogHeader>
        <AlertDialogFooter>
          <AlertDialogCancel asChild>
            <Button variant="outline" className="bg-secondary text-secondary-foreground hover:bg-secondary/80"> {/* Changed button styling */}
              Cancel
            </Button>
          </AlertDialogCancel>
          <AlertDialogAction asChild>
            <Button onClick={onConfirm} className="bg-primary hover:bg-primary/90 text-primary-foreground"> {/* Changed button styling */}
              I Understand & Continue
            </Button>
          </AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  );
};

export default DisclaimerDialog;